#branches:
#  except:
#    - /.*/
#  only:
#    - /^ci_*/

clone_depth: 1

install:
  - set PATH=C:\Ruby24\bin;%PATH%

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      WINDOWS_VISUAL_STUDIO_VERSION: 2017

build_script:
  - bash ./build_windows.sh

artifacts:
  - path: projects\extc\artifacts
    name: extc_lib_windows
