environment:
  matrix:
    - RUBY_VERSION: 26

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build_script:
  - bash ./build_appveyor.sh "%PLATFORM%" "%CONFIGURATION%"

skip_tags: true
