branches:
  except:
    - /.*/
  only:
    - /^ci_*/

clone_depth: 1

install:
  - set PATH=C:\Ruby24\bin;%PATH%

image:
  - Visual Studio 2017

build_script:
  - bash ./build_windows.sh

artifacts:
  - path: projects\extc\artifacts
    name: extc_lib_windows
