install:
  - set PATH=C:\Ruby24\bin;%PATH%

image:
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
  - bash ./build_appveyor.sh

artifacts:
  - path: projects\extc\lib
    name: lib\extc_lib_windows

skip_tags: true
