image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build_script:
  - bash ./setup.sh "%APPVEYOR_BUILD_WORKER_IMAGE%" "%PLATFORM%" "%CONFIGURATION%"

skip_tags: true
