version: 2.1
workflows:
  version: 2
  tagged-build:
    jobs:
      - build_centos7:
          filters:
            tags:
              only: /^ci_*/
      - build_ubuntu18:
          filters:
            tags:
              only: /^ci_*/
      - build_android:
          filters:
            tags:
              only: /^ci_*/
_common: &common
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Build
          command: RUBY_VERSION=2.4.0 bash ./build_linux.sh
      - store_artifacts:
          path: ./projects/extc/artifacts
          destination: extc_lib_linux
jobs:
  build_centos7:
    <<: *common
    docker:
      - image: centos:7
  build_ubuntu18:
    <<: *common
    docker:
      - image: ubuntu:18.04
  build_android:
    docker:
      - image: ubuntu:18.04
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Build
          command: RUBY_VERSION=2.4.0 bash ./build_android.sh r10e
      - store_artifacts:
          path: ./projects/extc/artifacts
          destination: extc_lib_android
