version: 2.1
executors:
  centos7:
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
      PACKAGE_MANAGER: yum
    docker:
      - image: centos:7
  ubuntu18:
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
      PACKAGE_MANAGER: apt
    docker:
      - image: ubuntu:18.04
commands:
  build_linux:
    steps:
      - checkout
      - run:
          name: Build
          command: RUBY_VERSION=2.4.0 bash ./build_linux.sh
      - store_artifacts:
          path: ./projects/extc/artifacts
          destination: extc_lib_linux
jobs:
  build_centos7:
    executor: centos7
    steps:
      - build_linux
  build_ubuntu18:
    executor: ubuntu18
    steps:
      - build_linux
workflows:
  version: 2
  all:
    jobs:
      - build_centos7
      - build_ubuntu18
