version: 2
workflows:
  version: 2
  build:
    jobs:
      - build_linux
jobs:
  build_linux:
    docker:
      - image: centos:7
      - image: ubuntu:16.04
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Build
          command: RUBY_VERSION=2.4.0 bash ./build_linux.sh
      - store_artifacts:
          path: ./projects/extc/artifacts
          destination: extc_lib_linux
