version: 2
workflows:
  version: 2
  build:
    jobs:
      - build_centos7
      - build_ubuntu18
      - build_android
_common_linux: &common_linux
    filters:
      tags:
        only:
          - /^ci_*/
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Build
          command: RUBY_VERSION=2.4.0 bash ./build_linux.sh
      - store_artifacts:
          path: ./projects/extc/artifacts
          destination: extc_lib_linux
_common_android: &common_android
    filters:
      tags:
        only:
          - /^ci_*/
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Build
          command: RUBY_VERSION=2.4.0 bash ./build_android.sh r10e
      - store_artifacts:
          path: ./projects/extc/artifacts
          destination: extc_lib_android
jobs:
  build_centos7:
    <<: *common_linux
    docker:
      - image: centos:7
  build_ubuntu18:
    <<: *common_linux
    docker:
      - image: ubuntu:18.04
  build_android:
    <<: *common_android
    docker:
      - image: ubuntu:18.04
