version: 2
workflows:
  version: 2
  build:
    jobs:
      - build_centos7
      - build_ubuntu18
_common: &common
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      - run:
          name: Build
          command: RUBY_VERSION=2.4.0 bash ./build_linux.sh
      - store_artifacts:
          path: ./projects/extc/artifacts
          destination: extc_lib_linux
jobs:
  build_centos7:
    <<: *common
    docker:
      - image: centos:7
  build_ubuntu18:
    <<: *common
    docker:
      - image: ubuntu:18.04
